### ISSUE TITLE
Please update for the new API, using version 5.0.6

### ISSUE THREAD

**Issue by PvUtrix** [RocketChat/Apps.ClickUp#12]
Error: Deployment error: Failed to load the App "ClickUp" (b3252284-88b0-4ef4-b81c-3a644ed0e401) as it 
 ›   requires v1.32.0 of the App API however your server comes with v1.33.0. Please tell the author to update their App as it 
 ›   is out of date.

**Comment by mustafahasankhan** [comment]
Hi! Thanks for pointing it out. 
Will update the code and push it soon, turn notifications for this issue on so that you get informed.

**Comment by PvUtrix** [comment]
Hello Mustafa
Any estimate on the update? 
Very eager to check out your app.

I can see that the Rocket Chat API has been updated again it's v1.35.0 now for Ricket Chat 5.2.0
