### ISSUE TITLE
Packaging the app... ✖ 2023-04-03 22:29:34.925 WARN  App has native module(s) as dependency  ›   Error:    ⟿  Error src/lib/persistWorkspace.ts (11,10): Module '"../storage/users"' has no exported member   ›   'connect_user_to_clickup_uid'.

### ISSUE THREAD

**Issue by PvUtrix** [RocketChat/Apps.ClickUp#17]
Hello!

I'm trying to install on Rocket.Chat v6.0.0

Getting the following error.
![image](https://user-images.githubusercontent.com/32957084/229609734-2d8f998d-b6c9-4ef9-87be-b0a6d2702ae4.png)

Is this a compatibility issue, or I'm doing something wrong?

**Comment by mohdjami** [comment]
Hi @PvUtrix,
Once my linked PR gets merged, this issue will be resolved.
